# Embeddings
embeddings_model: "all-MiniLM-L6-v2"

# FAISS
faiss_index_path: "data/processed/faiss_index"

# Llama model
llama_model_path: "models/llama_model.bin"
llama_n_ctx: 2048
llama_n_batch: 8
llama_verbose: true

# Streamlit
streamlit_title: "RAG Chatbot with Llama CPP"